// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package catalog

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTenant = `-- name: ActivateTenant :exec
UPDATE tenants
SET is_active = true
WHERE slug = $1
`

func (q *Queries) ActivateTenant(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, activateTenant, slug)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
  name, slug, db_url, plan, owner_email
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, slug, db_url, plan, is_active, owner_email, created_at
`

type CreateTenantParams struct {
	Name       string `json:"name"`
	Slug       string `json:"slug"`
	DbUrl      string `json:"db_url"`
	Plan       string `json:"plan"`
	OwnerEmail string `json:"owner_email"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (*Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.DbUrl,
		arg.Plan,
		arg.OwnerEmail,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbUrl,
		&i.Plan,
		&i.IsActive,
		&i.OwnerEmail,
		&i.CreatedAt,
	)
	return &i, err
}

const deactivateTenant = `-- name: DeactivateTenant :exec
UPDATE tenants
SET is_active = false
WHERE slug = $1
`

func (q *Queries) DeactivateTenant(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deactivateTenant, slug)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants
WHERE slug = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteTenant, slug)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, db_url, plan, is_active, owner_email, created_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id int64) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbUrl,
		&i.Plan,
		&i.IsActive,
		&i.OwnerEmail,
		&i.CreatedAt,
	)
	return &i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, db_url, plan, is_active, owner_email, created_at FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DbUrl,
		&i.Plan,
		&i.IsActive,
		&i.OwnerEmail,
		&i.CreatedAt,
	)
	return &i, err
}

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT tenant_id, clinic_name, primary_color, secondary_color, logo_url, enabled_modules, updated_at FROM tenant_settings
WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID int64) (*TenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, tenantID)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.ClinicName,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.LogoUrl,
		&i.EnabledModules,
		&i.UpdatedAt,
	)
	return &i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, name, slug, db_url, plan, is_active, owner_email, created_at FROM tenants
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveTenants(ctx context.Context) ([]*Tenant, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbUrl,
			&i.Plan,
			&i.IsActive,
			&i.OwnerEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTenants = `-- name: ListAllTenants :many
SELECT id, name, slug, db_url, plan, is_active, owner_email, created_at FROM tenants
ORDER BY name
`

func (q *Queries) ListAllTenants(ctx context.Context) ([]*Tenant, error) {
	rows, err := q.db.Query(ctx, listAllTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DbUrl,
			&i.Plan,
			&i.IsActive,
			&i.OwnerEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (
    tenant_id, clinic_name, primary_color, secondary_color, logo_url, enabled_modules, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (tenant_id) DO UPDATE SET
    clinic_name = EXCLUDED.clinic_name,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    logo_url = EXCLUDED.logo_url,
    enabled_modules = EXCLUDED.enabled_modules,
    updated_at = NOW()
RETURNING tenant_id, clinic_name, primary_color, secondary_color, logo_url, enabled_modules, updated_at
`

type UpsertTenantSettingsParams struct {
	TenantID       int64       `json:"tenant_id"`
	ClinicName     string      `json:"clinic_name"`
	PrimaryColor   string      `json:"primary_color"`
	SecondaryColor string      `json:"secondary_color"`
	LogoUrl        pgtype.Text `json:"logo_url"`
	EnabledModules []string    `json:"enabled_modules"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (*TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings,
		arg.TenantID,
		arg.ClinicName,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.LogoUrl,
		arg.EnabledModules,
	)
	var i TenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.ClinicName,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.LogoUrl,
		&i.EnabledModules,
		&i.UpdatedAt,
	)
	return &i, err
}
