// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (client_id, patient_id, vet_id, resource_id, start_time, end_time, reason, notes, status, type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, client_id, patient_id, vet_id, resource_id, start_time, end_time, reason, notes, status, type, created_at, updated_at
`

type CreateAppointmentParams struct {
	ClientID   int64              `json:"client_id"`
	PatientID  int64              `json:"patient_id"`
	VetID      pgtype.Int8        `json:"vet_id"`
	ResourceID pgtype.Int8        `json:"resource_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Reason     pgtype.Text        `json:"reason"`
	Notes      pgtype.Text        `json:"notes"`
	Status     string             `json:"status"`
	Type       string             `json:"type"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (*Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ClientID,
		arg.PatientID,
		arg.VetID,
		arg.ResourceID,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
		arg.Notes,
		arg.Status,
		arg.Type,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PatientID,
		&i.VetID,
		&i.ResourceID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT
    a.id, a.client_id, a.patient_id, a.vet_id, a.resource_id, a.start_time, a.end_time, a.reason, a.notes, a.status, a.type, a.created_at, a.updated_at,
    c.first_name AS client_first_name, c.last_name AS client_last_name, c.phone AS client_phone,
    p.name AS patient_name, p.species AS patient_species, p.id AS patient_db_id,
    u.username AS vet_username, u.first_name AS vet_first_name, u.last_name AS vet_last_name
FROM appointments a
JOIN clients c ON a.client_id = c.id
JOIN patients p ON a.patient_id = p.id
LEFT JOIN users u ON a.vet_id = u.id
WHERE a.id = $1
`

type GetAppointmentByIDRow struct {
	ID              int64              `json:"id"`
	ClientID        int64              `json:"client_id"`
	PatientID       int64              `json:"patient_id"`
	VetID           pgtype.Int8        `json:"vet_id"`
	ResourceID      pgtype.Int8        `json:"resource_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Reason          pgtype.Text        `json:"reason"`
	Notes           pgtype.Text        `json:"notes"`
	Status          string             `json:"status"`
	Type            string             `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClientFirstName string             `json:"client_first_name"`
	ClientLastName  string             `json:"client_last_name"`
	ClientPhone     pgtype.Text        `json:"client_phone"`
	PatientName     string             `json:"patient_name"`
	PatientSpecies  string             `json:"patient_species"`
	PatientDbID     int64              `json:"patient_db_id"`
	VetUsername     pgtype.Text        `json:"vet_username"`
	VetFirstName    pgtype.Text        `json:"vet_first_name"`
	VetLastName     pgtype.Text        `json:"vet_last_name"`
}

func (q *Queries) GetAppointmentByID(ctx context.Context, id int64) (*GetAppointmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i GetAppointmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PatientID,
		&i.VetID,
		&i.ResourceID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientFirstName,
		&i.ClientLastName,
		&i.ClientPhone,
		&i.PatientName,
		&i.PatientSpecies,
		&i.PatientDbID,
		&i.VetUsername,
		&i.VetFirstName,
		&i.VetLastName,
	)
	return &i, err
}

const getNextAppointmentForVet = `-- name: GetNextAppointmentForVet :one
SELECT
    a.id, a.client_id, a.patient_id, a.vet_id, a.resource_id, a.start_time, a.end_time, a.reason, a.notes, a.status, a.type, a.created_at, a.updated_at,
    c.first_name AS client_first_name, c.last_name AS client_last_name,
    p.name AS patient_name
FROM appointments a
JOIN clients c ON a.client_id = c.id
JOIN patients p ON a.patient_id = p.id
WHERE a.vet_id = $1
  AND a.start_time > NOW()
  AND a.status NOT IN ('CANCELLED', 'COMPLETED')
ORDER BY a.start_time ASC
LIMIT 1
`

type GetNextAppointmentForVetRow struct {
	ID              int64              `json:"id"`
	ClientID        int64              `json:"client_id"`
	PatientID       int64              `json:"patient_id"`
	VetID           pgtype.Int8        `json:"vet_id"`
	ResourceID      pgtype.Int8        `json:"resource_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Reason          pgtype.Text        `json:"reason"`
	Notes           pgtype.Text        `json:"notes"`
	Status          string             `json:"status"`
	Type            string             `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClientFirstName string             `json:"client_first_name"`
	ClientLastName  string             `json:"client_last_name"`
	PatientName     string             `json:"patient_name"`
}

func (q *Queries) GetNextAppointmentForVet(ctx context.Context, vetID pgtype.Int8) (*GetNextAppointmentForVetRow, error) {
	row := q.db.QueryRow(ctx, getNextAppointmentForVet, vetID)
	var i GetNextAppointmentForVetRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PatientID,
		&i.VetID,
		&i.ResourceID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientFirstName,
		&i.ClientLastName,
		&i.PatientName,
	)
	return &i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT
    a.id, a.client_id, a.patient_id, a.vet_id, a.resource_id, a.start_time, a.end_time, a.reason, a.notes, a.status, a.type, a.created_at, a.updated_at,
    c.first_name AS client_first_name, c.last_name AS client_last_name, c.phone AS client_phone,
    p.name AS patient_name, p.species AS patient_species,
    u.username AS vet_username, u.first_name AS vet_first_name, u.last_name AS vet_last_name
FROM appointments a
JOIN clients c ON a.client_id = c.id
JOIN patients p ON a.patient_id = p.id
LEFT JOIN users u ON a.vet_id = u.id
ORDER BY a.start_time DESC
`

type ListAppointmentsRow struct {
	ID              int64              `json:"id"`
	ClientID        int64              `json:"client_id"`
	PatientID       int64              `json:"patient_id"`
	VetID           pgtype.Int8        `json:"vet_id"`
	ResourceID      pgtype.Int8        `json:"resource_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Reason          pgtype.Text        `json:"reason"`
	Notes           pgtype.Text        `json:"notes"`
	Status          string             `json:"status"`
	Type            string             `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClientFirstName string             `json:"client_first_name"`
	ClientLastName  string             `json:"client_last_name"`
	ClientPhone     pgtype.Text        `json:"client_phone"`
	PatientName     string             `json:"patient_name"`
	PatientSpecies  string             `json:"patient_species"`
	VetUsername     pgtype.Text        `json:"vet_username"`
	VetFirstName    pgtype.Text        `json:"vet_first_name"`
	VetLastName     pgtype.Text        `json:"vet_last_name"`
}

func (q *Queries) ListAppointments(ctx context.Context) ([]*ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAppointmentsRow{}
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.PatientID,
			&i.VetID,
			&i.ResourceID,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.Notes,
			&i.Status,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientFirstName,
			&i.ClientLastName,
			&i.ClientPhone,
			&i.PatientName,
			&i.PatientSpecies,
			&i.VetUsername,
			&i.VetFirstName,
			&i.VetLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignAppointments = `-- name: ReassignAppointments :exec
UPDATE appointments SET vet_id = $2, updated_at = NOW()
WHERE vet_id = $1
`

type ReassignAppointmentsParams struct {
	VetID   pgtype.Int8 `json:"vet_id"`
	VetID_2 pgtype.Int8 `json:"vet_id_2"`
}

func (q *Queries) ReassignAppointments(ctx context.Context, arg ReassignAppointmentsParams) error {
	_, err := q.db.Exec(ctx, reassignAppointments, arg.VetID, arg.VetID_2)
	return err
}

const searchAppointments = `-- name: SearchAppointments :many
SELECT
    a.id, a.client_id, a.patient_id, a.vet_id, a.resource_id, a.start_time, a.end_time, a.reason, a.notes, a.status, a.type, a.created_at, a.updated_at,
    c.first_name AS client_first_name, c.last_name AS client_last_name,
    p.name AS patient_name,
    u.first_name AS vet_first_name, u.last_name AS vet_last_name
FROM appointments a
JOIN clients c ON a.client_id = c.id
JOIN patients p ON a.patient_id = p.id
LEFT JOIN users u ON a.vet_id = u.id
WHERE
    c.first_name ILIKE '%' || $1 || '%'
    OR c.last_name ILIKE '%' || $1 || '%'
    OR p.name ILIKE '%' || $1 || '%'
    OR a.reason ILIKE '%' || $1 || '%'
ORDER BY a.start_time DESC
`

type SearchAppointmentsRow struct {
	ID              int64              `json:"id"`
	ClientID        int64              `json:"client_id"`
	PatientID       int64              `json:"patient_id"`
	VetID           pgtype.Int8        `json:"vet_id"`
	ResourceID      pgtype.Int8        `json:"resource_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	Reason          pgtype.Text        `json:"reason"`
	Notes           pgtype.Text        `json:"notes"`
	Status          string             `json:"status"`
	Type            string             `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClientFirstName string             `json:"client_first_name"`
	ClientLastName  string             `json:"client_last_name"`
	PatientName     string             `json:"patient_name"`
	VetFirstName    pgtype.Text        `json:"vet_first_name"`
	VetLastName     pgtype.Text        `json:"vet_last_name"`
}

func (q *Queries) SearchAppointments(ctx context.Context, dollar_1 pgtype.Text) ([]*SearchAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, searchAppointments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SearchAppointmentsRow{}
	for rows.Next() {
		var i SearchAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.PatientID,
			&i.VetID,
			&i.ResourceID,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.Notes,
			&i.Status,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientFirstName,
			&i.ClientLastName,
			&i.PatientName,
			&i.VetFirstName,
			&i.VetLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments SET
    client_id = $2,
    patient_id = $3,
    vet_id = $4,
    resource_id = $5,
    start_time = $6,
    end_time = $7,
    reason = $8,
    notes = $9,
    status = $10,
    type = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, patient_id, vet_id, resource_id, start_time, end_time, reason, notes, status, type, created_at, updated_at
`

type UpdateAppointmentParams struct {
	ID         int64              `json:"id"`
	ClientID   int64              `json:"client_id"`
	PatientID  int64              `json:"patient_id"`
	VetID      pgtype.Int8        `json:"vet_id"`
	ResourceID pgtype.Int8        `json:"resource_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Reason     pgtype.Text        `json:"reason"`
	Notes      pgtype.Text        `json:"notes"`
	Status     string             `json:"status"`
	Type       string             `json:"type"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (*Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointment,
		arg.ID,
		arg.ClientID,
		arg.PatientID,
		arg.VetID,
		arg.ResourceID,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
		arg.Notes,
		arg.Status,
		arg.Type,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PatientID,
		&i.VetID,
		&i.ResourceID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
