// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredRefreshTokens = `-- name: CleanExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW()
`

func (q *Queries) CleanExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredRefreshTokens)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, email, first_name, last_name, role_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, email, first_name, last_name, is_active, role_id, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Email        pgtype.Text `json:"email"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	RoleID       pgtype.Int8 `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, permissions FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Permissions)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.username, u.password_hash, u.email, u.first_name, u.last_name, u.is_active, u.role_id, u.created_at, u.updated_at, r.name AS role_name, r.permissions AS role_permissions
FROM users u
JOIN roles r ON u.role_id = r.id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID              int64              `json:"id"`
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	Email           pgtype.Text        `json:"email"`
	FirstName       pgtype.Text        `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	IsActive        bool               `json:"is_active"`
	RoleID          pgtype.Int8        `json:"role_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RoleName        string             `json:"role_name"`
	RolePermissions []string           `json:"role_permissions"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RolePermissions,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT u.id, u.username, u.password_hash, u.email, u.first_name, u.last_name, u.is_active, u.role_id, u.created_at, u.updated_at, r.name AS role_name, r.permissions AS role_permissions
FROM users u
JOIN roles r ON u.role_id = r.id
WHERE u.username = $1 AND u.is_active = true
`

type GetUserByUsernameRow struct {
	ID              int64              `json:"id"`
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	Email           pgtype.Text        `json:"email"`
	FirstName       pgtype.Text        `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	IsActive        bool               `json:"is_active"`
	RoleID          pgtype.Int8        `json:"role_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RoleName        string             `json:"role_name"`
	RolePermissions []string           `json:"role_permissions"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.RolePermissions,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.username, u.password_hash, u.email, u.first_name, u.last_name, u.is_active, u.role_id, u.created_at, u.updated_at, r.name AS role_name
FROM users u
JOIN roles r ON u.role_id = r.id
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Email        pgtype.Text        `json:"email"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	IsActive     bool               `json:"is_active"`
	RoleID       pgtype.Int8        `json:"role_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	RoleName     string             `json:"role_name"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]*ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVets = `-- name: ListVets :many
SELECT u.id, u.username, u.password_hash, u.email, u.first_name, u.last_name, u.is_active, u.role_id, u.created_at, u.updated_at, r.name AS role_name
FROM users u
JOIN roles r ON u.role_id = r.id
WHERE r.name = 'VET' AND u.is_active = true
ORDER BY u.first_name
`

type ListVetsRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Email        pgtype.Text        `json:"email"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	IsActive     bool               `json:"is_active"`
	RoleID       pgtype.Int8        `json:"role_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	RoleName     string             `json:"role_name"`
}

func (q *Queries) ListVets(ctx context.Context) ([]*ListVetsRow, error) {
	rows, err := q.db.Query(ctx, listVets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListVetsRow{}
	for rows.Next() {
		var i ListVetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    first_name = COALESCE($3, first_name),
    last_name = COALESCE($4, last_name),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, password_hash, email, first_name, last_name, is_active, role_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID        int64       `json:"id"`
	Email     pgtype.Text `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	IsActive  pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
