// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (first_name, last_name, email, phone, address, afm, adt, gdpr_consent, is_stray_caretaker)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, first_name, last_name, email, phone, address, afm, adt, gdpr_consent, balance, is_stray_caretaker, created_at, updated_at
`

type CreateClientParams struct {
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Email            string      `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Address          pgtype.Text `json:"address"`
	Afm              pgtype.Text `json:"afm"`
	Adt              pgtype.Text `json:"adt"`
	GdprConsent      pgtype.Bool `json:"gdpr_consent"`
	IsStrayCaretaker pgtype.Bool `json:"is_stray_caretaker"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (*Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Afm,
		arg.Adt,
		arg.GdprConsent,
		arg.IsStrayCaretaker,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Afm,
		&i.Adt,
		&i.GdprConsent,
		&i.Balance,
		&i.IsStrayCaretaker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, first_name, last_name, email, phone, address, afm, adt, gdpr_consent, balance, is_stray_caretaker, created_at, updated_at FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id int64) (*Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Afm,
		&i.Adt,
		&i.GdprConsent,
		&i.Balance,
		&i.IsStrayCaretaker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listClients = `-- name: ListClients :many
SELECT c.id, c.first_name, c.last_name, c.email, c.phone, c.address, c.afm, c.adt, c.gdpr_consent, c.balance, c.is_stray_caretaker, c.created_at, c.updated_at,
    COUNT(p.id)::INTEGER AS pet_count
FROM clients c
LEFT JOIN patients p ON p.client_id = c.id
GROUP BY c.id
ORDER BY c.last_name, c.first_name
`

type ListClientsRow struct {
	ID               int64              `json:"id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	Address          pgtype.Text        `json:"address"`
	Afm              pgtype.Text        `json:"afm"`
	Adt              pgtype.Text        `json:"adt"`
	GdprConsent      pgtype.Bool        `json:"gdpr_consent"`
	Balance          float64            `json:"balance"`
	IsStrayCaretaker pgtype.Bool        `json:"is_stray_caretaker"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PetCount         int32              `json:"pet_count"`
}

func (q *Queries) ListClients(ctx context.Context) ([]*ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Afm,
			&i.Adt,
			&i.GdprConsent,
			&i.Balance,
			&i.IsStrayCaretaker,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT c.id, c.first_name, c.last_name, c.email, c.phone, c.address, c.afm, c.adt, c.gdpr_consent, c.balance, c.is_stray_caretaker, c.created_at, c.updated_at,
    COUNT(p.id)::INTEGER AS pet_count
FROM clients c
LEFT JOIN patients p ON p.client_id = c.id
WHERE
    c.first_name ILIKE '%' || $1 || '%'
    OR c.last_name ILIKE '%' || $1 || '%'
    OR c.email ILIKE '%' || $1 || '%'
    OR c.phone ILIKE '%' || $1 || '%'
GROUP BY c.id
ORDER BY c.last_name, c.first_name
`

type SearchClientsRow struct {
	ID               int64              `json:"id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	Address          pgtype.Text        `json:"address"`
	Afm              pgtype.Text        `json:"afm"`
	Adt              pgtype.Text        `json:"adt"`
	GdprConsent      pgtype.Bool        `json:"gdpr_consent"`
	Balance          float64            `json:"balance"`
	IsStrayCaretaker pgtype.Bool        `json:"is_stray_caretaker"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PetCount         int32              `json:"pet_count"`
}

func (q *Queries) SearchClients(ctx context.Context, dollar_1 pgtype.Text) ([]*SearchClientsRow, error) {
	rows, err := q.db.Query(ctx, searchClients, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SearchClientsRow{}
	for rows.Next() {
		var i SearchClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Afm,
			&i.Adt,
			&i.GdprConsent,
			&i.Balance,
			&i.IsStrayCaretaker,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
    first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    address = $6,
    afm = $7,
    adt = $8,
    gdpr_consent = $9,
    is_stray_caretaker = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, address, afm, adt, gdpr_consent, balance, is_stray_caretaker, created_at, updated_at
`

type UpdateClientParams struct {
	ID               int64       `json:"id"`
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Email            string      `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Address          pgtype.Text `json:"address"`
	Afm              pgtype.Text `json:"afm"`
	Adt              pgtype.Text `json:"adt"`
	GdprConsent      pgtype.Bool `json:"gdpr_consent"`
	IsStrayCaretaker pgtype.Bool `json:"is_stray_caretaker"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (*Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Afm,
		arg.Adt,
		arg.GdprConsent,
		arg.IsStrayCaretaker,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Afm,
		&i.Adt,
		&i.GdprConsent,
		&i.Balance,
		&i.IsStrayCaretaker,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
