// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard.sql

package db

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM clients)::INTEGER AS total_clients,
    (SELECT COUNT(*) FROM patients WHERE is_deceased = false)::INTEGER AS total_patients,
    (SELECT COUNT(*) FROM appointments WHERE DATE(start_time) = CURRENT_DATE)::INTEGER AS today_appointments,
    (SELECT COUNT(*) FROM appointments
     WHERE start_time >= DATE_TRUNC('week', CURRENT_DATE)
       AND start_time < DATE_TRUNC('week', CURRENT_DATE) + INTERVAL '7 days'
    )::INTEGER AS week_appointments
`

type GetDashboardStatsRow struct {
	TotalClients      int32 `json:"total_clients"`
	TotalPatients     int32 `json:"total_patients"`
	TodayAppointments int32 `json:"today_appointments"`
	WeekAppointments  int32 `json:"week_appointments"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (*GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalClients,
		&i.TotalPatients,
		&i.TodayAppointments,
		&i.WeekAppointments,
	)
	return &i, err
}
