// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medical_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedicalRecord = `-- name: CreateMedicalRecord :one
INSERT INTO medical_records (appointment_id, patient_id, diagnosis, treatment, notes, symptoms, weight, temperature)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, appointment_id, patient_id, diagnosis, treatment, notes, symptoms, weight, temperature, created_at, updated_at
`

type CreateMedicalRecordParams struct {
	AppointmentID pgtype.Int8   `json:"appointment_id"`
	PatientID     int64         `json:"patient_id"`
	Diagnosis     pgtype.Text   `json:"diagnosis"`
	Treatment     pgtype.Text   `json:"treatment"`
	Notes         pgtype.Text   `json:"notes"`
	Symptoms      pgtype.Text   `json:"symptoms"`
	Weight        pgtype.Float8 `json:"weight"`
	Temperature   pgtype.Float8 `json:"temperature"`
}

func (q *Queries) CreateMedicalRecord(ctx context.Context, arg CreateMedicalRecordParams) (*MedicalRecord, error) {
	row := q.db.QueryRow(ctx, createMedicalRecord,
		arg.AppointmentID,
		arg.PatientID,
		arg.Diagnosis,
		arg.Treatment,
		arg.Notes,
		arg.Symptoms,
		arg.Weight,
		arg.Temperature,
	)
	var i MedicalRecord
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.PatientID,
		&i.Diagnosis,
		&i.Treatment,
		&i.Notes,
		&i.Symptoms,
		&i.Weight,
		&i.Temperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMedicalRecordByAppointment = `-- name: GetMedicalRecordByAppointment :one
SELECT id, appointment_id, patient_id, diagnosis, treatment, notes, symptoms, weight, temperature, created_at, updated_at FROM medical_records WHERE appointment_id = $1
`

func (q *Queries) GetMedicalRecordByAppointment(ctx context.Context, appointmentID pgtype.Int8) (*MedicalRecord, error) {
	row := q.db.QueryRow(ctx, getMedicalRecordByAppointment, appointmentID)
	var i MedicalRecord
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.PatientID,
		&i.Diagnosis,
		&i.Treatment,
		&i.Notes,
		&i.Symptoms,
		&i.Weight,
		&i.Temperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listMedicalRecordsByClient = `-- name: ListMedicalRecordsByClient :many
SELECT mr.id, mr.appointment_id, mr.patient_id, mr.diagnosis, mr.treatment, mr.notes, mr.symptoms, mr.weight, mr.temperature, mr.created_at, mr.updated_at, a.type AS appointment_type, a.start_time AS visit_date,
    p.name AS patient_name
FROM medical_records mr
LEFT JOIN appointments a ON mr.appointment_id = a.id
JOIN patients p ON mr.patient_id = p.id
WHERE p.client_id = $1
ORDER BY mr.created_at DESC
`

type ListMedicalRecordsByClientRow struct {
	ID              int64              `json:"id"`
	AppointmentID   pgtype.Int8        `json:"appointment_id"`
	PatientID       int64              `json:"patient_id"`
	Diagnosis       pgtype.Text        `json:"diagnosis"`
	Treatment       pgtype.Text        `json:"treatment"`
	Notes           pgtype.Text        `json:"notes"`
	Symptoms        pgtype.Text        `json:"symptoms"`
	Weight          pgtype.Float8      `json:"weight"`
	Temperature     pgtype.Float8      `json:"temperature"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	VisitDate       pgtype.Timestamptz `json:"visit_date"`
	PatientName     string             `json:"patient_name"`
}

func (q *Queries) ListMedicalRecordsByClient(ctx context.Context, clientID int64) ([]*ListMedicalRecordsByClientRow, error) {
	rows, err := q.db.Query(ctx, listMedicalRecordsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMedicalRecordsByClientRow{}
	for rows.Next() {
		var i ListMedicalRecordsByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.PatientID,
			&i.Diagnosis,
			&i.Treatment,
			&i.Notes,
			&i.Symptoms,
			&i.Weight,
			&i.Temperature,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentType,
			&i.VisitDate,
			&i.PatientName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicalRecordsByPatient = `-- name: ListMedicalRecordsByPatient :many
SELECT mr.id, mr.appointment_id, mr.patient_id, mr.diagnosis, mr.treatment, mr.notes, mr.symptoms, mr.weight, mr.temperature, mr.created_at, mr.updated_at, a.type AS appointment_type, a.start_time AS visit_date
FROM medical_records mr
LEFT JOIN appointments a ON mr.appointment_id = a.id
WHERE mr.patient_id = $1
ORDER BY mr.created_at DESC
`

type ListMedicalRecordsByPatientRow struct {
	ID              int64              `json:"id"`
	AppointmentID   pgtype.Int8        `json:"appointment_id"`
	PatientID       int64              `json:"patient_id"`
	Diagnosis       pgtype.Text        `json:"diagnosis"`
	Treatment       pgtype.Text        `json:"treatment"`
	Notes           pgtype.Text        `json:"notes"`
	Symptoms        pgtype.Text        `json:"symptoms"`
	Weight          pgtype.Float8      `json:"weight"`
	Temperature     pgtype.Float8      `json:"temperature"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppointmentType pgtype.Text        `json:"appointment_type"`
	VisitDate       pgtype.Timestamptz `json:"visit_date"`
}

func (q *Queries) ListMedicalRecordsByPatient(ctx context.Context, patientID int64) ([]*ListMedicalRecordsByPatientRow, error) {
	rows, err := q.db.Query(ctx, listMedicalRecordsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListMedicalRecordsByPatientRow{}
	for rows.Next() {
		var i ListMedicalRecordsByPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.PatientID,
			&i.Diagnosis,
			&i.Treatment,
			&i.Notes,
			&i.Symptoms,
			&i.Weight,
			&i.Temperature,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentType,
			&i.VisitDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedicalRecord = `-- name: UpdateMedicalRecord :one
UPDATE medical_records SET
    diagnosis = $2,
    treatment = $3,
    notes = $4,
    symptoms = $5,
    weight = $6,
    temperature = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, appointment_id, patient_id, diagnosis, treatment, notes, symptoms, weight, temperature, created_at, updated_at
`

type UpdateMedicalRecordParams struct {
	ID          int64         `json:"id"`
	Diagnosis   pgtype.Text   `json:"diagnosis"`
	Treatment   pgtype.Text   `json:"treatment"`
	Notes       pgtype.Text   `json:"notes"`
	Symptoms    pgtype.Text   `json:"symptoms"`
	Weight      pgtype.Float8 `json:"weight"`
	Temperature pgtype.Float8 `json:"temperature"`
}

func (q *Queries) UpdateMedicalRecord(ctx context.Context, arg UpdateMedicalRecordParams) (*MedicalRecord, error) {
	row := q.db.QueryRow(ctx, updateMedicalRecord,
		arg.ID,
		arg.Diagnosis,
		arg.Treatment,
		arg.Notes,
		arg.Symptoms,
		arg.Weight,
		arg.Temperature,
	)
	var i MedicalRecord
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.PatientID,
		&i.Diagnosis,
		&i.Treatment,
		&i.Notes,
		&i.Symptoms,
		&i.Weight,
		&i.Temperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
