// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Appointment struct {
	ID         int64              `json:"id"`
	ClientID   int64              `json:"client_id"`
	PatientID  int64              `json:"patient_id"`
	VetID      pgtype.Int8        `json:"vet_id"`
	ResourceID pgtype.Int8        `json:"resource_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Reason     pgtype.Text        `json:"reason"`
	Notes      pgtype.Text        `json:"notes"`
	Status     string             `json:"status"`
	Type       string             `json:"type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Client struct {
	ID               int64              `json:"id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	Address          pgtype.Text        `json:"address"`
	Afm              pgtype.Text        `json:"afm"`
	Adt              pgtype.Text        `json:"adt"`
	GdprConsent      pgtype.Bool        `json:"gdpr_consent"`
	Balance          float64            `json:"balance"`
	IsStrayCaretaker pgtype.Bool        `json:"is_stray_caretaker"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MedicalRecord struct {
	ID            int64              `json:"id"`
	AppointmentID pgtype.Int8        `json:"appointment_id"`
	PatientID     int64              `json:"patient_id"`
	Diagnosis     pgtype.Text        `json:"diagnosis"`
	Treatment     pgtype.Text        `json:"treatment"`
	Notes         pgtype.Text        `json:"notes"`
	Symptoms      pgtype.Text        `json:"symptoms"`
	Weight        pgtype.Float8      `json:"weight"`
	Temperature   pgtype.Float8      `json:"temperature"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Patient struct {
	ID                int64              `json:"id"`
	ClientID          int64              `json:"client_id"`
	Name              string             `json:"name"`
	Species           string             `json:"species"`
	Breed             pgtype.Text        `json:"breed"`
	Sex               pgtype.Text        `json:"sex"`
	BirthDate         pgtype.Date        `json:"birth_date"`
	IsDobApproximate  pgtype.Bool        `json:"is_dob_approximate"`
	MicrochipNumber   pgtype.Text        `json:"microchip_number"`
	MicrochipDate     pgtype.Date        `json:"microchip_date"`
	IsSterilized      pgtype.Bool        `json:"is_sterilized"`
	SterilizationDate pgtype.Date        `json:"sterilization_date"`
	Weight            pgtype.Float4      `json:"weight"`
	IsDeceased        pgtype.Bool        `json:"is_deceased"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PatientAlert struct {
	ID          int64              `json:"id"`
	PatientID   int64              `json:"patient_id"`
	AlertType   string             `json:"alert_type"`
	Description string             `json:"description"`
	Severity    string             `json:"severity"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Resource struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	ColorCode pgtype.Text `json:"color_code"`
}

type Role struct {
	ID          int64    `json:"id"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

type Tenant struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	DbUrl      string             `json:"db_url"`
	Plan       string             `json:"plan"`
	IsActive   bool               `json:"is_active"`
	OwnerEmail string             `json:"owner_email"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TenantSetting struct {
	TenantID       int64              `json:"tenant_id"`
	ClinicName     string             `json:"clinic_name"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	LogoUrl        pgtype.Text        `json:"logo_url"`
	EnabledModules []string           `json:"enabled_modules"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Email        pgtype.Text        `json:"email"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	IsActive     bool               `json:"is_active"`
	RoleID       pgtype.Int8        `json:"role_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ClientID     pgtype.Int8        `json:"client_id"`
	OidcSub      pgtype.Text        `json:"oidc_sub"`
}
