// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCUser = `-- name: CreateOIDCUser :one
INSERT INTO users (username, password_hash, email, first_name, last_name, is_active, role_id, client_id, oidc_sub)
VALUES ($1, '', $2, $3, $4, true, (SELECT id FROM roles WHERE name = 'CLIENT'), $5, $6)
RETURNING id, username, email, first_name, last_name, is_active, role_id, client_id, oidc_sub
`

type CreateOIDCUserParams struct {
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	ClientID  pgtype.Int8 `json:"client_id"`
	OidcSub   pgtype.Text `json:"oidc_sub"`
}

type CreateOIDCUserRow struct {
	ID        int64       `json:"id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	IsActive  bool        `json:"is_active"`
	RoleID    pgtype.Int8 `json:"role_id"`
	ClientID  pgtype.Int8 `json:"client_id"`
	OidcSub   pgtype.Text `json:"oidc_sub"`
}

// Creates a new user for OIDC login (no password, CLIENT role)
func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (*CreateOIDCUserRow, error) {
	row := q.db.QueryRow(ctx, createOIDCUser,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.ClientID,
		arg.OidcSub,
	)
	var i CreateOIDCUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.ClientID,
		&i.OidcSub,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, first_name, last_name, is_active, role_id, client_id, oidc_sub
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID        int64       `json:"id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	IsActive  bool        `json:"is_active"`
	RoleID    pgtype.Int8 `json:"role_id"`
	ClientID  pgtype.Int8 `json:"client_id"`
	OidcSub   pgtype.Text `json:"oidc_sub"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.ClientID,
		&i.OidcSub,
	)
	return &i, err
}

const getUserByOIDCSub = `-- name: GetUserByOIDCSub :one
SELECT id, username, email, first_name, last_name, is_active, role_id, client_id, oidc_sub
FROM users
WHERE oidc_sub = $1
LIMIT 1
`

type GetUserByOIDCSubRow struct {
	ID        int64       `json:"id"`
	Username  string      `json:"username"`
	Email     pgtype.Text `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	IsActive  bool        `json:"is_active"`
	RoleID    pgtype.Int8 `json:"role_id"`
	ClientID  pgtype.Int8 `json:"client_id"`
	OidcSub   pgtype.Text `json:"oidc_sub"`
}

func (q *Queries) GetUserByOIDCSub(ctx context.Context, oidcSub pgtype.Text) (*GetUserByOIDCSubRow, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSub, oidcSub)
	var i GetUserByOIDCSubRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.RoleID,
		&i.ClientID,
		&i.OidcSub,
	)
	return &i, err
}

const setUserOIDCSub = `-- name: SetUserOIDCSub :exec
UPDATE users
SET oidc_sub = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserOIDCSubParams struct {
	ID      int64       `json:"id"`
	OidcSub pgtype.Text `json:"oidc_sub"`
}

func (q *Queries) SetUserOIDCSub(ctx context.Context, arg SetUserOIDCSubParams) error {
	_, err := q.db.Exec(ctx, setUserOIDCSub, arg.ID, arg.OidcSub)
	return err
}
