// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
    client_id, name, species, breed, sex,
    birth_date, is_dob_approximate,
    microchip_number, microchip_date,
    is_sterilized, sterilization_date, weight
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, client_id, name, species, breed, sex, birth_date, is_dob_approximate, microchip_number, microchip_date, is_sterilized, sterilization_date, weight, is_deceased, created_at, updated_at
`

type CreatePatientParams struct {
	ClientID          int64         `json:"client_id"`
	Name              string        `json:"name"`
	Species           string        `json:"species"`
	Breed             pgtype.Text   `json:"breed"`
	Sex               pgtype.Text   `json:"sex"`
	BirthDate         pgtype.Date   `json:"birth_date"`
	IsDobApproximate  pgtype.Bool   `json:"is_dob_approximate"`
	MicrochipNumber   pgtype.Text   `json:"microchip_number"`
	MicrochipDate     pgtype.Date   `json:"microchip_date"`
	IsSterilized      pgtype.Bool   `json:"is_sterilized"`
	SterilizationDate pgtype.Date   `json:"sterilization_date"`
	Weight            pgtype.Float4 `json:"weight"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.ClientID,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Sex,
		arg.BirthDate,
		arg.IsDobApproximate,
		arg.MicrochipNumber,
		arg.MicrochipDate,
		arg.IsSterilized,
		arg.SterilizationDate,
		arg.Weight,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.BirthDate,
		&i.IsDobApproximate,
		&i.MicrochipNumber,
		&i.MicrochipDate,
		&i.IsSterilized,
		&i.SterilizationDate,
		&i.Weight,
		&i.IsDeceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients WHERE id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePatient, id)
	return err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, client_id, name, species, breed, sex, birth_date, is_dob_approximate, microchip_number, microchip_date, is_sterilized, sterilization_date, weight, is_deceased, created_at, updated_at FROM patients WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id int64) (*Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.BirthDate,
		&i.IsDobApproximate,
		&i.MicrochipNumber,
		&i.MicrochipDate,
		&i.IsSterilized,
		&i.SterilizationDate,
		&i.Weight,
		&i.IsDeceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllPatients = `-- name: ListAllPatients :many
SELECT p.id, p.client_id, p.name, p.species, p.breed, p.sex, p.birth_date, p.is_dob_approximate, p.microchip_number, p.microchip_date, p.is_sterilized, p.sterilization_date, p.weight, p.is_deceased, p.created_at, p.updated_at, c.first_name AS owner_first_name, c.last_name AS owner_last_name
FROM patients p
JOIN clients c ON p.client_id = c.id
ORDER BY p.name
`

type ListAllPatientsRow struct {
	ID                int64              `json:"id"`
	ClientID          int64              `json:"client_id"`
	Name              string             `json:"name"`
	Species           string             `json:"species"`
	Breed             pgtype.Text        `json:"breed"`
	Sex               pgtype.Text        `json:"sex"`
	BirthDate         pgtype.Date        `json:"birth_date"`
	IsDobApproximate  pgtype.Bool        `json:"is_dob_approximate"`
	MicrochipNumber   pgtype.Text        `json:"microchip_number"`
	MicrochipDate     pgtype.Date        `json:"microchip_date"`
	IsSterilized      pgtype.Bool        `json:"is_sterilized"`
	SterilizationDate pgtype.Date        `json:"sterilization_date"`
	Weight            pgtype.Float4      `json:"weight"`
	IsDeceased        pgtype.Bool        `json:"is_deceased"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OwnerFirstName    string             `json:"owner_first_name"`
	OwnerLastName     string             `json:"owner_last_name"`
}

func (q *Queries) ListAllPatients(ctx context.Context) ([]*ListAllPatientsRow, error) {
	rows, err := q.db.Query(ctx, listAllPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAllPatientsRow{}
	for rows.Next() {
		var i ListAllPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Sex,
			&i.BirthDate,
			&i.IsDobApproximate,
			&i.MicrochipNumber,
			&i.MicrochipDate,
			&i.IsSterilized,
			&i.SterilizationDate,
			&i.Weight,
			&i.IsDeceased,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerFirstName,
			&i.OwnerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsByOwner = `-- name: ListPatientsByOwner :many
SELECT id, client_id, name, species, breed, sex, birth_date, is_dob_approximate, microchip_number, microchip_date, is_sterilized, sterilization_date, weight, is_deceased, created_at, updated_at FROM patients
WHERE client_id = $1
ORDER BY name
`

func (q *Queries) ListPatientsByOwner(ctx context.Context, clientID int64) ([]*Patient, error) {
	rows, err := q.db.Query(ctx, listPatientsByOwner, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Species,
			&i.Breed,
			&i.Sex,
			&i.BirthDate,
			&i.IsDobApproximate,
			&i.MicrochipNumber,
			&i.MicrochipDate,
			&i.IsSterilized,
			&i.SterilizationDate,
			&i.Weight,
			&i.IsDeceased,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPatientDeceased = `-- name: MarkPatientDeceased :one
UPDATE patients SET is_deceased = true, updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, name, species, breed, sex, birth_date, is_dob_approximate, microchip_number, microchip_date, is_sterilized, sterilization_date, weight, is_deceased, created_at, updated_at
`

func (q *Queries) MarkPatientDeceased(ctx context.Context, id int64) (*Patient, error) {
	row := q.db.QueryRow(ctx, markPatientDeceased, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.BirthDate,
		&i.IsDobApproximate,
		&i.MicrochipNumber,
		&i.MicrochipDate,
		&i.IsSterilized,
		&i.SterilizationDate,
		&i.Weight,
		&i.IsDeceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const transferPatient = `-- name: TransferPatient :one
UPDATE patients SET client_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, name, species, breed, sex, birth_date, is_dob_approximate, microchip_number, microchip_date, is_sterilized, sterilization_date, weight, is_deceased, created_at, updated_at
`

type TransferPatientParams struct {
	ID       int64 `json:"id"`
	ClientID int64 `json:"client_id"`
}

func (q *Queries) TransferPatient(ctx context.Context, arg TransferPatientParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, transferPatient, arg.ID, arg.ClientID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.BirthDate,
		&i.IsDobApproximate,
		&i.MicrochipNumber,
		&i.MicrochipDate,
		&i.IsSterilized,
		&i.SterilizationDate,
		&i.Weight,
		&i.IsDeceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients SET
    name = $2,
    species = $3,
    breed = $4,
    sex = $5,
    birth_date = $6,
    is_dob_approximate = $7,
    microchip_number = $8,
    microchip_date = $9,
    is_sterilized = $10,
    sterilization_date = $11,
    weight = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, name, species, breed, sex, birth_date, is_dob_approximate, microchip_number, microchip_date, is_sterilized, sterilization_date, weight, is_deceased, created_at, updated_at
`

type UpdatePatientParams struct {
	ID                int64         `json:"id"`
	Name              string        `json:"name"`
	Species           string        `json:"species"`
	Breed             pgtype.Text   `json:"breed"`
	Sex               pgtype.Text   `json:"sex"`
	BirthDate         pgtype.Date   `json:"birth_date"`
	IsDobApproximate  pgtype.Bool   `json:"is_dob_approximate"`
	MicrochipNumber   pgtype.Text   `json:"microchip_number"`
	MicrochipDate     pgtype.Date   `json:"microchip_date"`
	IsSterilized      pgtype.Bool   `json:"is_sterilized"`
	SterilizationDate pgtype.Date   `json:"sterilization_date"`
	Weight            pgtype.Float4 `json:"weight"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.Name,
		arg.Species,
		arg.Breed,
		arg.Sex,
		arg.BirthDate,
		arg.IsDobApproximate,
		arg.MicrochipNumber,
		arg.MicrochipDate,
		arg.IsSterilized,
		arg.SterilizationDate,
		arg.Weight,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.BirthDate,
		&i.IsDobApproximate,
		&i.MicrochipNumber,
		&i.MicrochipDate,
		&i.IsSterilized,
		&i.SterilizationDate,
		&i.Weight,
		&i.IsDeceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
