// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: patient_alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO patient_alerts (patient_id, alert_type, description, severity, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, patient_id, alert_type, description, severity, is_active, created_at
`

type CreateAlertParams struct {
	PatientID   int64       `json:"patient_id"`
	AlertType   string      `json:"alert_type"`
	Description string      `json:"description"`
	Severity    string      `json:"severity"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (*PatientAlert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.PatientID,
		arg.AlertType,
		arg.Description,
		arg.Severity,
		arg.IsActive,
	)
	var i PatientAlert
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.AlertType,
		&i.Description,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM patient_alerts WHERE id = $1
`

func (q *Queries) DeleteAlert(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAlert, id)
	return err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, patient_id, alert_type, description, severity, is_active, created_at FROM patient_alerts WHERE id = $1
`

func (q *Queries) GetAlertByID(ctx context.Context, id int64) (*PatientAlert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, id)
	var i PatientAlert
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.AlertType,
		&i.Description,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}

const listAlertsByPatient = `-- name: ListAlertsByPatient :many
SELECT id, patient_id, alert_type, description, severity, is_active, created_at FROM patient_alerts
WHERE patient_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAlertsByPatient(ctx context.Context, patientID int64) ([]*PatientAlert, error) {
	rows, err := q.db.Query(ctx, listAlertsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PatientAlert{}
	for rows.Next() {
		var i PatientAlert
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.AlertType,
			&i.Description,
			&i.Severity,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE patient_alerts SET
    alert_type  = $2,
    description = $3,
    severity    = $4,
    is_active   = $5
WHERE id = $1
RETURNING id, patient_id, alert_type, description, severity, is_active, created_at
`

type UpdateAlertParams struct {
	ID          int64       `json:"id"`
	AlertType   string      `json:"alert_type"`
	Description string      `json:"description"`
	Severity    string      `json:"severity"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (*PatientAlert, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.ID,
		arg.AlertType,
		arg.Description,
		arg.Severity,
		arg.IsActive,
	)
	var i PatientAlert
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.AlertType,
		&i.Description,
		&i.Severity,
		&i.IsActive,
		&i.CreatedAt,
	)
	return &i, err
}
